# Generated by Django 4.2.8 on 2023-12-17 12:27

from django.db import migrations
import task_list.models


class Migration(migrations.Migration):
    dependencies = [
        ("task_list", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="tagss",
        ),
        migrations.AddField(
            model_name="todo",
            name="tag",
            field=task_list.models.TagListField(blank=True, null=True),
        ),
    ]
